name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add target
      run: rustup target add wasm32-wasip1
    - name: Build
      run: cargo build --verbose --target wasm32-wasip1
    - name: upload WASM file
      uses: actions/upload-artifact@v4
      with:
        name: "markdown rendering plugin file"
        path: target/wasm32-wasip1/debug/lblp_markdown_plugin.wasm
